/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BecomeACaptainRouteImport } from './routes/become-a-captain'
import { Route as BrandStoryRouteImport } from './routes/brand-story'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedBookingRouteImport } from './routes/_authenticated/booking'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPayoutsStatusRouteImport } from './routes/_authenticated/payouts-status'
import { Route as AuthenticatedResolutionCenterRouteImport } from './routes/_authenticated/resolution-center'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as CaptainsProfileRouteImport } from './routes/captains.profile'
import { Route as ChartersIndexRouteImport } from './routes/charters.index'
import { Route as ChartersCharterIdRouteImport } from './routes/charters.$charterId'
import { Route as ChartersSearchRouteImport } from './routes/charters.search'
import { Route as ExploreVerticalRouteImport } from './routes/explore.$vertical'
import { Route as GuidesProfileRouteImport } from './routes/guides.profile'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as MarketplaceProductIdRouteImport } from './routes/marketplace.$productId'
import { Route as ServicesSearchRouteImport } from './routes/services.search'
import { Route as AuthenticatedBookingsDetailRouteImport } from './routes/_authenticated/bookings.detail'
import { Route as AuthenticatedTripsDetailRouteImport } from './routes/_authenticated/trips.detail'
import { Route as ApiPublicFishxWebhookRouteImport } from './routes/api/public/fishx-webhook'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AuthenticatedCaptainChartersNewRouteImport } from './routes/_authenticated/captain.charters.new'
import { Route as AuthenticatedCaptainPackagesPackageIdRouteImport } from './routes/_authenticated/captain.packages.$packageId'
import { Route as AuthenticatedShopProductsNewRouteImport } from './routes/_authenticated/shop.products.new'
import { Route as ApiPublicAvatarsSplatRouteImport } from './routes/api/public/avatars/$'
import { Route as ApiPublicHooksBookingTimersRouteImport } from './routes/api/public/hooks/booking-timers'
import { Route as ApiPublicHooksDispatchEventsRouteImport } from './routes/api/public/hooks/dispatch-events'
import { Route as ApiPublicHooksListingMetricsRouteImport } from './routes/api/public/hooks/listing-metrics'
import { Route as ApiPublicHooksReleaseEscrowRouteImport } from './routes/api/public/hooks/release-escrow'
import { Route as ApiPublicHooksRemindersRouteImport } from './routes/api/public/hooks/reminders'
import { Route as ApiPublicHooksSyncCronSecretRouteImport } from './routes/api/public/hooks/sync-cron-secret'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'
import { Route as AuthenticatedCaptainChartersCharterIdEditRouteImport } from './routes/_authenticated/captain.charters.$charterId.edit'
import { Route as AuthenticatedShopProductsProductIdEditRouteImport } from './routes/_authenticated/shop.products.$productId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeACaptainRoute = BecomeACaptainRouteImport.update({
  id: '/become-a-captain',
  path: '/become-a-captain',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandStoryRoute = BrandStoryRouteImport.update({
  id: '/brand-story',
  path: '/brand-story',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingRoute = AuthenticatedBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayoutsStatusRoute =
  AuthenticatedPayoutsStatusRouteImport.update({
    id: '/payouts-status',
    path: '/payouts-status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResolutionCenterRoute =
  AuthenticatedResolutionCenterRouteImport.update({
    id: '/resolution-center',
    path: '/resolution-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainsProfileRoute = CaptainsProfileRouteImport.update({
  id: '/captains/profile',
  path: '/captains/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartersIndexRoute = ChartersIndexRouteImport.update({
  id: '/charters/',
  path: '/charters/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartersCharterIdRoute = ChartersCharterIdRouteImport.update({
  id: '/charters/$charterId',
  path: '/charters/$charterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartersSearchRoute = ChartersSearchRouteImport.update({
  id: '/charters/search',
  path: '/charters/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreVerticalRoute = ExploreVerticalRouteImport.update({
  id: '/explore/$vertical',
  path: '/explore/$vertical',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesProfileRoute = GuidesProfileRouteImport.update({
  id: '/guides/profile',
  path: '/guides/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceProductIdRoute = MarketplaceProductIdRouteImport.update({
  id: '/marketplace/$productId',
  path: '/marketplace/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSearchRoute = ServicesSearchRouteImport.update({
  id: '/services/search',
  path: '/services/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBookingsDetailRoute =
  AuthenticatedBookingsDetailRouteImport.update({
    id: '/bookings/detail',
    path: '/bookings/detail',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTripsDetailRoute =
  AuthenticatedTripsDetailRouteImport.update({
    id: '/trips/detail',
    path: '/trips/detail',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicFishxWebhookRoute = ApiPublicFishxWebhookRouteImport.update({
  id: '/api/public/fishx-webhook',
  path: '/api/public/fishx-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCaptainChartersNewRoute =
  AuthenticatedCaptainChartersNewRouteImport.update({
    id: '/captain/charters/new',
    path: '/captain/charters/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaptainPackagesPackageIdRoute =
  AuthenticatedCaptainPackagesPackageIdRouteImport.update({
    id: '/captain/packages/$packageId',
    path: '/captain/packages/$packageId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShopProductsNewRoute =
  AuthenticatedShopProductsNewRouteImport.update({
    id: '/shop/products/new',
    path: '/shop/products/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAvatarsSplatRoute = ApiPublicAvatarsSplatRouteImport.update({
  id: '/api/public/avatars/$',
  path: '/api/public/avatars/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBookingTimersRoute =
  ApiPublicHooksBookingTimersRouteImport.update({
    id: '/api/public/hooks/booking-timers',
    path: '/api/public/hooks/booking-timers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchEventsRoute =
  ApiPublicHooksDispatchEventsRouteImport.update({
    id: '/api/public/hooks/dispatch-events',
    path: '/api/public/hooks/dispatch-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksListingMetricsRoute =
  ApiPublicHooksListingMetricsRouteImport.update({
    id: '/api/public/hooks/listing-metrics',
    path: '/api/public/hooks/listing-metrics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReleaseEscrowRoute =
  ApiPublicHooksReleaseEscrowRouteImport.update({
    id: '/api/public/hooks/release-escrow',
    path: '/api/public/hooks/release-escrow',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRemindersRoute = ApiPublicHooksRemindersRouteImport.update({
  id: '/api/public/hooks/reminders',
  path: '/api/public/hooks/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncCronSecretRoute =
  ApiPublicHooksSyncCronSecretRouteImport.update({
    id: '/api/public/hooks/sync-cron-secret',
    path: '/api/public/hooks/sync-cron-secret',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCaptainChartersCharterIdEditRoute =
  AuthenticatedCaptainChartersCharterIdEditRouteImport.update({
    id: '/captain/charters/$charterId/edit',
    path: '/captain/charters/$charterId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShopProductsProductIdEditRoute =
  AuthenticatedShopProductsProductIdEditRouteImport.update({
    id: '/shop/products/$productId/edit',
    path: '/shop/products/$productId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-a-captain': typeof BecomeACaptainRoute
  '/brand-story': typeof BrandStoryRoute
  '/discover': typeof DiscoverRoute
  '/how-it-works': typeof HowItWorksRoute
  '/trust': typeof TrustRoute
  '/account': typeof AuthenticatedAccountRoute
  '/booking': typeof AuthenticatedBookingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/payouts-status': typeof AuthenticatedPayoutsStatusRoute
  '/resolution-center': typeof AuthenticatedResolutionCenterRoute
  '/review': typeof AuthenticatedReviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/b/$slug': typeof BSlugRoute
  '/captains/profile': typeof CaptainsProfileRoute
  '/charters/$charterId': typeof ChartersCharterIdRoute
  '/charters/search': typeof ChartersSearchRoute
  '/explore/$vertical': typeof ExploreVerticalRoute
  '/guides/profile': typeof GuidesProfileRoute
  '/marketplace/$productId': typeof MarketplaceProductIdRoute
  '/services/search': typeof ServicesSearchRoute
  '/charters/': typeof ChartersIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/bookings/detail': typeof AuthenticatedBookingsDetailRoute
  '/trips/detail': typeof AuthenticatedTripsDetailRoute
  '/api/public/fishx-webhook': typeof ApiPublicFishxWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/captain/charters/new': typeof AuthenticatedCaptainChartersNewRoute
  '/captain/packages/$packageId': typeof AuthenticatedCaptainPackagesPackageIdRoute
  '/shop/products/new': typeof AuthenticatedShopProductsNewRoute
  '/api/public/avatars/$': typeof ApiPublicAvatarsSplatRoute
  '/api/public/hooks/booking-timers': typeof ApiPublicHooksBookingTimersRoute
  '/api/public/hooks/dispatch-events': typeof ApiPublicHooksDispatchEventsRoute
  '/api/public/hooks/listing-metrics': typeof ApiPublicHooksListingMetricsRoute
  '/api/public/hooks/release-escrow': typeof ApiPublicHooksReleaseEscrowRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
  '/api/public/hooks/sync-cron-secret': typeof ApiPublicHooksSyncCronSecretRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/captain/charters/$charterId/edit': typeof AuthenticatedCaptainChartersCharterIdEditRoute
  '/shop/products/$productId/edit': typeof AuthenticatedShopProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-a-captain': typeof BecomeACaptainRoute
  '/brand-story': typeof BrandStoryRoute
  '/discover': typeof DiscoverRoute
  '/how-it-works': typeof HowItWorksRoute
  '/trust': typeof TrustRoute
  '/account': typeof AuthenticatedAccountRoute
  '/booking': typeof AuthenticatedBookingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/payouts-status': typeof AuthenticatedPayoutsStatusRoute
  '/resolution-center': typeof AuthenticatedResolutionCenterRoute
  '/review': typeof AuthenticatedReviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/b/$slug': typeof BSlugRoute
  '/captains/profile': typeof CaptainsProfileRoute
  '/charters/$charterId': typeof ChartersCharterIdRoute
  '/charters/search': typeof ChartersSearchRoute
  '/explore/$vertical': typeof ExploreVerticalRoute
  '/guides/profile': typeof GuidesProfileRoute
  '/marketplace/$productId': typeof MarketplaceProductIdRoute
  '/services/search': typeof ServicesSearchRoute
  '/charters': typeof ChartersIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/bookings/detail': typeof AuthenticatedBookingsDetailRoute
  '/trips/detail': typeof AuthenticatedTripsDetailRoute
  '/api/public/fishx-webhook': typeof ApiPublicFishxWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/captain/charters/new': typeof AuthenticatedCaptainChartersNewRoute
  '/captain/packages/$packageId': typeof AuthenticatedCaptainPackagesPackageIdRoute
  '/shop/products/new': typeof AuthenticatedShopProductsNewRoute
  '/api/public/avatars/$': typeof ApiPublicAvatarsSplatRoute
  '/api/public/hooks/booking-timers': typeof ApiPublicHooksBookingTimersRoute
  '/api/public/hooks/dispatch-events': typeof ApiPublicHooksDispatchEventsRoute
  '/api/public/hooks/listing-metrics': typeof ApiPublicHooksListingMetricsRoute
  '/api/public/hooks/release-escrow': typeof ApiPublicHooksReleaseEscrowRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
  '/api/public/hooks/sync-cron-secret': typeof ApiPublicHooksSyncCronSecretRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/captain/charters/$charterId/edit': typeof AuthenticatedCaptainChartersCharterIdEditRoute
  '/shop/products/$productId/edit': typeof AuthenticatedShopProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-a-captain': typeof BecomeACaptainRoute
  '/brand-story': typeof BrandStoryRoute
  '/discover': typeof DiscoverRoute
  '/how-it-works': typeof HowItWorksRoute
  '/trust': typeof TrustRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/booking': typeof AuthenticatedBookingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/payouts-status': typeof AuthenticatedPayoutsStatusRoute
  '/_authenticated/resolution-center': typeof AuthenticatedResolutionCenterRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/b/$slug': typeof BSlugRoute
  '/captains/profile': typeof CaptainsProfileRoute
  '/charters/$charterId': typeof ChartersCharterIdRoute
  '/charters/search': typeof ChartersSearchRoute
  '/explore/$vertical': typeof ExploreVerticalRoute
  '/guides/profile': typeof GuidesProfileRoute
  '/marketplace/$productId': typeof MarketplaceProductIdRoute
  '/services/search': typeof ServicesSearchRoute
  '/charters/': typeof ChartersIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/_authenticated/bookings/detail': typeof AuthenticatedBookingsDetailRoute
  '/_authenticated/trips/detail': typeof AuthenticatedTripsDetailRoute
  '/api/public/fishx-webhook': typeof ApiPublicFishxWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/captain/charters/new': typeof AuthenticatedCaptainChartersNewRoute
  '/_authenticated/captain/packages/$packageId': typeof AuthenticatedCaptainPackagesPackageIdRoute
  '/_authenticated/shop/products/new': typeof AuthenticatedShopProductsNewRoute
  '/api/public/avatars/$': typeof ApiPublicAvatarsSplatRoute
  '/api/public/hooks/booking-timers': typeof ApiPublicHooksBookingTimersRoute
  '/api/public/hooks/dispatch-events': typeof ApiPublicHooksDispatchEventsRoute
  '/api/public/hooks/listing-metrics': typeof ApiPublicHooksListingMetricsRoute
  '/api/public/hooks/release-escrow': typeof ApiPublicHooksReleaseEscrowRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
  '/api/public/hooks/sync-cron-secret': typeof ApiPublicHooksSyncCronSecretRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/_authenticated/captain/charters/$charterId/edit': typeof AuthenticatedCaptainChartersCharterIdEditRoute
  '/_authenticated/shop/products/$productId/edit': typeof AuthenticatedShopProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/become-a-captain'
    | '/brand-story'
    | '/discover'
    | '/how-it-works'
    | '/trust'
    | '/account'
    | '/booking'
    | '/dashboard'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/payouts-status'
    | '/resolution-center'
    | '/review'
    | '/settings'
    | '/b/$slug'
    | '/captains/profile'
    | '/charters/$charterId'
    | '/charters/search'
    | '/explore/$vertical'
    | '/guides/profile'
    | '/marketplace/$productId'
    | '/services/search'
    | '/charters/'
    | '/marketplace/'
    | '/bookings/detail'
    | '/trips/detail'
    | '/api/public/fishx-webhook'
    | '/api/public/stripe-webhook'
    | '/captain/charters/new'
    | '/captain/packages/$packageId'
    | '/shop/products/new'
    | '/api/public/avatars/$'
    | '/api/public/hooks/booking-timers'
    | '/api/public/hooks/dispatch-events'
    | '/api/public/hooks/listing-metrics'
    | '/api/public/hooks/release-escrow'
    | '/api/public/hooks/reminders'
    | '/api/public/hooks/sync-cron-secret'
    | '/api/public/media/$'
    | '/captain/charters/$charterId/edit'
    | '/shop/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/become-a-captain'
    | '/brand-story'
    | '/discover'
    | '/how-it-works'
    | '/trust'
    | '/account'
    | '/booking'
    | '/dashboard'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/payouts-status'
    | '/resolution-center'
    | '/review'
    | '/settings'
    | '/b/$slug'
    | '/captains/profile'
    | '/charters/$charterId'
    | '/charters/search'
    | '/explore/$vertical'
    | '/guides/profile'
    | '/marketplace/$productId'
    | '/services/search'
    | '/charters'
    | '/marketplace'
    | '/bookings/detail'
    | '/trips/detail'
    | '/api/public/fishx-webhook'
    | '/api/public/stripe-webhook'
    | '/captain/charters/new'
    | '/captain/packages/$packageId'
    | '/shop/products/new'
    | '/api/public/avatars/$'
    | '/api/public/hooks/booking-timers'
    | '/api/public/hooks/dispatch-events'
    | '/api/public/hooks/listing-metrics'
    | '/api/public/hooks/release-escrow'
    | '/api/public/hooks/reminders'
    | '/api/public/hooks/sync-cron-secret'
    | '/api/public/media/$'
    | '/captain/charters/$charterId/edit'
    | '/shop/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/become-a-captain'
    | '/brand-story'
    | '/discover'
    | '/how-it-works'
    | '/trust'
    | '/_authenticated/account'
    | '/_authenticated/booking'
    | '/_authenticated/dashboard'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/payouts-status'
    | '/_authenticated/resolution-center'
    | '/_authenticated/review'
    | '/_authenticated/settings'
    | '/b/$slug'
    | '/captains/profile'
    | '/charters/$charterId'
    | '/charters/search'
    | '/explore/$vertical'
    | '/guides/profile'
    | '/marketplace/$productId'
    | '/services/search'
    | '/charters/'
    | '/marketplace/'
    | '/_authenticated/bookings/detail'
    | '/_authenticated/trips/detail'
    | '/api/public/fishx-webhook'
    | '/api/public/stripe-webhook'
    | '/_authenticated/captain/charters/new'
    | '/_authenticated/captain/packages/$packageId'
    | '/_authenticated/shop/products/new'
    | '/api/public/avatars/$'
    | '/api/public/hooks/booking-timers'
    | '/api/public/hooks/dispatch-events'
    | '/api/public/hooks/listing-metrics'
    | '/api/public/hooks/release-escrow'
    | '/api/public/hooks/reminders'
    | '/api/public/hooks/sync-cron-secret'
    | '/api/public/media/$'
    | '/_authenticated/captain/charters/$charterId/edit'
    | '/_authenticated/shop/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BecomeACaptainRoute: typeof BecomeACaptainRoute
  BrandStoryRoute: typeof BrandStoryRoute
  DiscoverRoute: typeof DiscoverRoute
  HowItWorksRoute: typeof HowItWorksRoute
  TrustRoute: typeof TrustRoute
  BSlugRoute: typeof BSlugRoute
  CaptainsProfileRoute: typeof CaptainsProfileRoute
  ChartersCharterIdRoute: typeof ChartersCharterIdRoute
  ChartersSearchRoute: typeof ChartersSearchRoute
  ExploreVerticalRoute: typeof ExploreVerticalRoute
  GuidesProfileRoute: typeof GuidesProfileRoute
  MarketplaceProductIdRoute: typeof MarketplaceProductIdRoute
  ServicesSearchRoute: typeof ServicesSearchRoute
  ChartersIndexRoute: typeof ChartersIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  ApiPublicFishxWebhookRoute: typeof ApiPublicFishxWebhookRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicAvatarsSplatRoute: typeof ApiPublicAvatarsSplatRoute
  ApiPublicHooksBookingTimersRoute: typeof ApiPublicHooksBookingTimersRoute
  ApiPublicHooksDispatchEventsRoute: typeof ApiPublicHooksDispatchEventsRoute
  ApiPublicHooksListingMetricsRoute: typeof ApiPublicHooksListingMetricsRoute
  ApiPublicHooksReleaseEscrowRoute: typeof ApiPublicHooksReleaseEscrowRoute
  ApiPublicHooksRemindersRoute: typeof ApiPublicHooksRemindersRoute
  ApiPublicHooksSyncCronSecretRoute: typeof ApiPublicHooksSyncCronSecretRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-captain': {
      id: '/become-a-captain'
      path: '/become-a-captain'
      fullPath: '/become-a-captain'
      preLoaderRoute: typeof BecomeACaptainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-story': {
      id: '/brand-story'
      path: '/brand-story'
      fullPath: '/brand-story'
      preLoaderRoute: typeof BrandStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/booking': {
      id: '/_authenticated/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof AuthenticatedBookingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payouts-status': {
      id: '/_authenticated/payouts-status'
      path: '/payouts-status'
      fullPath: '/payouts-status'
      preLoaderRoute: typeof AuthenticatedPayoutsStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resolution-center': {
      id: '/_authenticated/resolution-center'
      path: '/resolution-center'
      fullPath: '/resolution-center'
      preLoaderRoute: typeof AuthenticatedResolutionCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captains/profile': {
      id: '/captains/profile'
      path: '/captains/profile'
      fullPath: '/captains/profile'
      preLoaderRoute: typeof CaptainsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charters/': {
      id: '/charters/'
      path: '/charters'
      fullPath: '/charters/'
      preLoaderRoute: typeof ChartersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charters/$charterId': {
      id: '/charters/$charterId'
      path: '/charters/$charterId'
      fullPath: '/charters/$charterId'
      preLoaderRoute: typeof ChartersCharterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charters/search': {
      id: '/charters/search'
      path: '/charters/search'
      fullPath: '/charters/search'
      preLoaderRoute: typeof ChartersSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$vertical': {
      id: '/explore/$vertical'
      path: '/explore/$vertical'
      fullPath: '/explore/$vertical'
      preLoaderRoute: typeof ExploreVerticalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/profile': {
      id: '/guides/profile'
      path: '/guides/profile'
      fullPath: '/guides/profile'
      preLoaderRoute: typeof GuidesProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$productId': {
      id: '/marketplace/$productId'
      path: '/marketplace/$productId'
      fullPath: '/marketplace/$productId'
      preLoaderRoute: typeof MarketplaceProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/search': {
      id: '/services/search'
      path: '/services/search'
      fullPath: '/services/search'
      preLoaderRoute: typeof ServicesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bookings/detail': {
      id: '/_authenticated/bookings/detail'
      path: '/bookings/detail'
      fullPath: '/bookings/detail'
      preLoaderRoute: typeof AuthenticatedBookingsDetailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trips/detail': {
      id: '/_authenticated/trips/detail'
      path: '/trips/detail'
      fullPath: '/trips/detail'
      preLoaderRoute: typeof AuthenticatedTripsDetailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/fishx-webhook': {
      id: '/api/public/fishx-webhook'
      path: '/api/public/fishx-webhook'
      fullPath: '/api/public/fishx-webhook'
      preLoaderRoute: typeof ApiPublicFishxWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/captain/charters/new': {
      id: '/_authenticated/captain/charters/new'
      path: '/captain/charters/new'
      fullPath: '/captain/charters/new'
      preLoaderRoute: typeof AuthenticatedCaptainChartersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/captain/packages/$packageId': {
      id: '/_authenticated/captain/packages/$packageId'
      path: '/captain/packages/$packageId'
      fullPath: '/captain/packages/$packageId'
      preLoaderRoute: typeof AuthenticatedCaptainPackagesPackageIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop/products/new': {
      id: '/_authenticated/shop/products/new'
      path: '/shop/products/new'
      fullPath: '/shop/products/new'
      preLoaderRoute: typeof AuthenticatedShopProductsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/avatars/$': {
      id: '/api/public/avatars/$'
      path: '/api/public/avatars/$'
      fullPath: '/api/public/avatars/$'
      preLoaderRoute: typeof ApiPublicAvatarsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/booking-timers': {
      id: '/api/public/hooks/booking-timers'
      path: '/api/public/hooks/booking-timers'
      fullPath: '/api/public/hooks/booking-timers'
      preLoaderRoute: typeof ApiPublicHooksBookingTimersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-events': {
      id: '/api/public/hooks/dispatch-events'
      path: '/api/public/hooks/dispatch-events'
      fullPath: '/api/public/hooks/dispatch-events'
      preLoaderRoute: typeof ApiPublicHooksDispatchEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/listing-metrics': {
      id: '/api/public/hooks/listing-metrics'
      path: '/api/public/hooks/listing-metrics'
      fullPath: '/api/public/hooks/listing-metrics'
      preLoaderRoute: typeof ApiPublicHooksListingMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/release-escrow': {
      id: '/api/public/hooks/release-escrow'
      path: '/api/public/hooks/release-escrow'
      fullPath: '/api/public/hooks/release-escrow'
      preLoaderRoute: typeof ApiPublicHooksReleaseEscrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reminders': {
      id: '/api/public/hooks/reminders'
      path: '/api/public/hooks/reminders'
      fullPath: '/api/public/hooks/reminders'
      preLoaderRoute: typeof ApiPublicHooksRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-cron-secret': {
      id: '/api/public/hooks/sync-cron-secret'
      path: '/api/public/hooks/sync-cron-secret'
      fullPath: '/api/public/hooks/sync-cron-secret'
      preLoaderRoute: typeof ApiPublicHooksSyncCronSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/captain/charters/$charterId/edit': {
      id: '/_authenticated/captain/charters/$charterId/edit'
      path: '/captain/charters/$charterId/edit'
      fullPath: '/captain/charters/$charterId/edit'
      preLoaderRoute: typeof AuthenticatedCaptainChartersCharterIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop/products/$productId/edit': {
      id: '/_authenticated/shop/products/$productId/edit'
      path: '/shop/products/$productId/edit'
      fullPath: '/shop/products/$productId/edit'
      preLoaderRoute: typeof AuthenticatedShopProductsProductIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedBookingRoute: typeof AuthenticatedBookingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPayoutsStatusRoute: typeof AuthenticatedPayoutsStatusRoute
  AuthenticatedResolutionCenterRoute: typeof AuthenticatedResolutionCenterRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedBookingsDetailRoute: typeof AuthenticatedBookingsDetailRoute
  AuthenticatedTripsDetailRoute: typeof AuthenticatedTripsDetailRoute
  AuthenticatedCaptainChartersNewRoute: typeof AuthenticatedCaptainChartersNewRoute
  AuthenticatedCaptainPackagesPackageIdRoute: typeof AuthenticatedCaptainPackagesPackageIdRoute
  AuthenticatedShopProductsNewRoute: typeof AuthenticatedShopProductsNewRoute
  AuthenticatedCaptainChartersCharterIdEditRoute: typeof AuthenticatedCaptainChartersCharterIdEditRoute
  AuthenticatedShopProductsProductIdEditRoute: typeof AuthenticatedShopProductsProductIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedBookingRoute: AuthenticatedBookingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPayoutsStatusRoute: AuthenticatedPayoutsStatusRoute,
  AuthenticatedResolutionCenterRoute: AuthenticatedResolutionCenterRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedBookingsDetailRoute: AuthenticatedBookingsDetailRoute,
  AuthenticatedTripsDetailRoute: AuthenticatedTripsDetailRoute,
  AuthenticatedCaptainChartersNewRoute: AuthenticatedCaptainChartersNewRoute,
  AuthenticatedCaptainPackagesPackageIdRoute:
    AuthenticatedCaptainPackagesPackageIdRoute,
  AuthenticatedShopProductsNewRoute: AuthenticatedShopProductsNewRoute,
  AuthenticatedCaptainChartersCharterIdEditRoute:
    AuthenticatedCaptainChartersCharterIdEditRoute,
  AuthenticatedShopProductsProductIdEditRoute:
    AuthenticatedShopProductsProductIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BecomeACaptainRoute: BecomeACaptainRoute,
  BrandStoryRoute: BrandStoryRoute,
  DiscoverRoute: DiscoverRoute,
  HowItWorksRoute: HowItWorksRoute,
  TrustRoute: TrustRoute,
  BSlugRoute: BSlugRoute,
  CaptainsProfileRoute: CaptainsProfileRoute,
  ChartersCharterIdRoute: ChartersCharterIdRoute,
  ChartersSearchRoute: ChartersSearchRoute,
  ExploreVerticalRoute: ExploreVerticalRoute,
  GuidesProfileRoute: GuidesProfileRoute,
  MarketplaceProductIdRoute: MarketplaceProductIdRoute,
  ServicesSearchRoute: ServicesSearchRoute,
  ChartersIndexRoute: ChartersIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  ApiPublicFishxWebhookRoute: ApiPublicFishxWebhookRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicAvatarsSplatRoute: ApiPublicAvatarsSplatRoute,
  ApiPublicHooksBookingTimersRoute: ApiPublicHooksBookingTimersRoute,
  ApiPublicHooksDispatchEventsRoute: ApiPublicHooksDispatchEventsRoute,
  ApiPublicHooksListingMetricsRoute: ApiPublicHooksListingMetricsRoute,
  ApiPublicHooksReleaseEscrowRoute: ApiPublicHooksReleaseEscrowRoute,
  ApiPublicHooksRemindersRoute: ApiPublicHooksRemindersRoute,
  ApiPublicHooksSyncCronSecretRoute: ApiPublicHooksSyncCronSecretRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
